-- Add comprehensive skin tone references from professional color chart
INSERT INTO public.skin_tone_references (hex_color, name, undertone, depth, category, source) VALUES
-- F Series (Fair with pink undertones)
('#F4E6D9', 'F463', 'cool', 'fair', 'fair', 'professional_chart'),
('#F0E1D4', 'F464', 'cool', 'fair', 'fair', 'professional_chart'),
('#ECDCCF', 'F465', 'cool', 'fair', 'fair', 'professional_chart'),
('#E8D7CA', 'F466', 'cool', 'light', 'light', 'professional_chart'),
('#E4D2C5', 'F467', 'cool', 'light', 'light', 'professional_chart'),
('#E0CDC0', 'F468', 'cool', 'light', 'light', 'professional_chart'),
('#DCC8BB', 'F469', 'cool', 'light', 'light', 'professional_chart'),
('#D8C3B6', 'F470', 'cool', 'light', 'light', 'professional_chart'),
('#D4BEB1', 'F471', 'cool', 'light', 'light', 'professional_chart'),
('#D0B9AC', 'F472', 'cool', 'medium', 'medium', 'professional_chart'),
('#CCB4A7', 'F473', 'cool', 'medium', 'medium', 'professional_chart'),
('#C8AFA2', 'F474', 'cool', 'medium', 'medium', 'professional_chart'),

-- G Series (Golden/warm fair tones)
('#F2E4D6', 'G463', 'warm', 'fair', 'fair', 'professional_chart'),
('#EEDFCD', 'G464', 'warm', 'fair', 'fair', 'professional_chart'),
('#EADAC4', 'G465', 'warm', 'fair', 'fair', 'professional_chart'),
('#E6D5BB', 'G466', 'warm', 'light', 'light', 'professional_chart'),
('#E2D0B2', 'G467', 'warm', 'light', 'light', 'professional_chart'),
('#DECBA9', 'G468', 'warm', 'light', 'light', 'professional_chart'),
('#DAC6A0', 'G469', 'warm', 'light', 'light', 'professional_chart'),
('#D6C197', 'G470', 'warm', 'light', 'light', 'professional_chart'),
('#D2BC8E', 'G471', 'warm', 'light', 'light', 'professional_chart'),
('#CEB785', 'G472', 'warm', 'medium', 'medium', 'professional_chart'),
('#CAB27C', 'G473', 'warm', 'medium', 'medium', 'professional_chart'),
('#C6AD73', 'G474', 'warm', 'medium', 'medium', 'professional_chart'),

-- H Series (Honey/neutral warm tones)
('#EDE2D2', 'H463', 'neutral', 'fair', 'fair', 'professional_chart'),
('#E9DDC9', 'H464', 'neutral', 'fair', 'fair', 'professional_chart'),
('#E5D8C0', 'H465', 'neutral', 'fair', 'fair', 'professional_chart'),
('#E1D3B7', 'H466', 'neutral', 'light', 'light', 'professional_chart'),
('#DDCEAE', 'H467', 'neutral', 'light', 'light', 'professional_chart'),
('#D9C9A5', 'H468', 'neutral', 'light', 'light', 'professional_chart'),
('#D5C49C', 'H469', 'neutral', 'light', 'light', 'professional_chart'),
('#D1BF93', 'H470', 'neutral', 'light', 'light', 'professional_chart'),
('#CDBA8A', 'H471', 'neutral', 'light', 'light', 'professional_chart'),
('#C9B581', 'H472', 'neutral', 'medium', 'medium', 'professional_chart'),
('#C5B078', 'H473', 'neutral', 'medium', 'medium', 'professional_chart'),
('#C1AB6F', 'H474', 'neutral', 'medium', 'medium', 'professional_chart'),

-- J Series (Warm beige tones)
('#E6DBD0', 'J463', 'warm', 'fair', 'fair', 'professional_chart'),
('#E2D6C7', 'J464', 'warm', 'fair', 'fair', 'professional_chart'),
('#DED1BE', 'J465', 'warm', 'fair', 'fair', 'professional_chart'),
('#DACCB5', 'J466', 'warm', 'light', 'light', 'professional_chart'),
('#D6C7AC', 'J467', 'warm', 'light', 'light', 'professional_chart'),
('#D2C2A3', 'J468', 'warm', 'light', 'light', 'professional_chart'),
('#CEBD9A', 'J469', 'warm', 'light', 'light', 'professional_chart'),
('#CAB891', 'J470', 'warm', 'light', 'light', 'professional_chart'),
('#C6B388', 'J471', 'warm', 'light', 'light', 'professional_chart'),
('#C2AE7F', 'J472', 'warm', 'medium', 'medium', 'professional_chart'),
('#BEA976', 'J473', 'warm', 'medium', 'medium', 'professional_chart'),
('#BAA46D', 'J474', 'warm', 'medium', 'medium', 'professional_chart'),

-- K Series (Medium warm tones)
('#DDD2C8', 'K463', 'warm', 'light', 'light', 'professional_chart'),
('#D9CDBF', 'K464', 'warm', 'light', 'light', 'professional_chart'),
('#D5C8B6', 'K465', 'warm', 'light', 'light', 'professional_chart'),
('#D1C3AD', 'K466', 'warm', 'light', 'light', 'professional_chart'),
('#CDBEA4', 'K467', 'warm', 'light', 'light', 'professional_chart'),
('#C9B99B', 'K468', 'warm', 'medium', 'medium', 'professional_chart'),
('#C5B492', 'K469', 'warm', 'medium', 'medium', 'professional_chart'),
('#C1AF89', 'K470', 'warm', 'medium', 'medium', 'professional_chart'),
('#BDAA80', 'K471', 'warm', 'medium', 'medium', 'professional_chart'),
('#B9A577', 'K472', 'warm', 'medium', 'medium', 'professional_chart'),
('#B5A06E', 'K473', 'warm', 'medium', 'medium', 'professional_chart'),
('#B19B65', 'K474', 'warm', 'medium', 'medium', 'professional_chart'),

-- L Series (Light olive/neutral tones)
('#D4C9BF', 'L463', 'olive', 'light', 'light', 'professional_chart'),
('#D0C4B6', 'L464', 'olive', 'light', 'light', 'professional_chart'),
('#CCBFAD', 'L465', 'olive', 'light', 'light', 'professional_chart'),
('#C8BAA4', 'L466', 'olive', 'light', 'light', 'professional_chart'),
('#C4B59B', 'L467', 'olive', 'medium', 'medium', 'professional_chart'),
('#C0B092', 'L468', 'olive', 'medium', 'medium', 'professional_chart'),
('#BCAB89', 'L469', 'olive', 'medium', 'medium', 'professional_chart'),
('#B8A680', 'L470', 'olive', 'medium', 'medium', 'professional_chart'),
('#B4A177', 'L471', 'olive', 'medium', 'medium', 'professional_chart'),
('#B09C6E', 'L472', 'olive', 'medium', 'medium', 'professional_chart'),
('#AC9765', 'L473', 'olive', 'medium', 'medium', 'professional_chart'),
('#A8925C', 'L474', 'olive', 'medium', 'medium', 'professional_chart'),

-- M Series (Medium warm brown tones)
('#C7BCAB', 'M463', 'warm', 'medium', 'medium', 'professional_chart'),
('#C3B7A2', 'M464', 'warm', 'medium', 'medium', 'professional_chart'),
('#BFB299', 'M465', 'warm', 'medium', 'medium', 'professional_chart'),
('#BBAD90', 'M466', 'warm', 'medium', 'medium', 'professional_chart'),
('#B7A887', 'M467', 'warm', 'medium', 'medium', 'professional_chart'),
('#B3A37E', 'M468', 'warm', 'medium', 'medium', 'professional_chart'),
('#AF9E75', 'M469', 'warm', 'medium', 'medium', 'professional_chart'),
('#AB996C', 'M470', 'warm', 'medium', 'medium', 'professional_chart'),
('#A79463', 'M471', 'warm', 'medium', 'medium', 'professional_chart'),
('#A38F5A', 'M472', 'warm', 'deep', 'deep', 'professional_chart'),
('#9F8A51', 'M473', 'warm', 'deep', 'deep', 'professional_chart'),
('#9B8548', 'M474', 'warm', 'deep', 'deep', 'professional_chart'),

-- N Series (Neutral brown tones)
('#BAB09F', 'N463', 'neutral', 'medium', 'medium', 'professional_chart'),
('#B6AB96', 'N464', 'neutral', 'medium', 'medium', 'professional_chart'),
('#B2A68D', 'N465', 'neutral', 'medium', 'medium', 'professional_chart'),
('#AEA184', 'N466', 'neutral', 'medium', 'medium', 'professional_chart'),
('#AA9C7B', 'N467', 'neutral', 'medium', 'medium', 'professional_chart'),
('#A69772', 'N468', 'neutral', 'medium', 'medium', 'professional_chart'),
('#A29269', 'N469', 'neutral', 'medium', 'medium', 'professional_chart'),
('#9E8D60', 'N470', 'neutral', 'medium', 'medium', 'professional_chart'),
('#9A8857', 'N471', 'neutral', 'deep', 'deep', 'professional_chart'),
('#96834E', 'N472', 'neutral', 'deep', 'deep', 'professional_chart'),
('#927E45', 'N473', 'neutral', 'deep', 'deep', 'professional_chart'),
('#8E793C', 'N474', 'neutral', 'deep', 'deep', 'professional_chart'),

-- S Series (Deep warm tones)
('#ADA396', 'S463', 'warm', 'medium', 'medium', 'professional_chart'),
('#A99E8D', 'S464', 'warm', 'medium', 'medium', 'professional_chart'),
('#A59984', 'S465', 'warm', 'medium', 'medium', 'professional_chart'),
('#A1947B', 'S466', 'warm', 'medium', 'medium', 'professional_chart'),
('#9D8F72', 'S467', 'warm', 'medium', 'medium', 'professional_chart'),
('#998A69', 'S468', 'warm', 'deep', 'deep', 'professional_chart'),
('#958560', 'S469', 'warm', 'deep', 'deep', 'professional_chart'),
('#918057', 'S470', 'warm', 'deep', 'deep', 'professional_chart'),
('#8D7B4E', 'S471', 'warm', 'deep', 'deep', 'professional_chart'),
('#897645', 'S472', 'warm', 'deep', 'deep', 'professional_chart'),
('#85713C', 'S473', 'warm', 'deep', 'deep', 'professional_chart'),
('#816C33', 'S474', 'warm', 'deep', 'deep', 'professional_chart'),

-- V Series (Deep neutral tones)
('#A0968D', 'V463', 'neutral', 'medium', 'medium', 'professional_chart'),
('#9C9184', 'V464', 'neutral', 'medium', 'medium', 'professional_chart'),
('#988C7B', 'V465', 'neutral', 'medium', 'medium', 'professional_chart'),
('#948772', 'V466', 'neutral', 'medium', 'medium', 'professional_chart'),
('#908269', 'V467', 'neutral', 'deep', 'deep', 'professional_chart'),
('#8C7D60', 'V468', 'neutral', 'deep', 'deep', 'professional_chart'),
('#887857', 'V469', 'neutral', 'deep', 'deep', 'professional_chart'),
('#84734E', 'V470', 'neutral', 'deep', 'deep', 'professional_chart'),
('#806E45', 'V471', 'neutral', 'deep', 'deep', 'professional_chart'),
('#7C693C', 'V472', 'neutral', 'deep', 'deep', 'professional_chart'),
('#786433', 'V473', 'neutral', 'deep', 'deep', 'professional_chart'),
('#745F2A', 'V474', 'neutral', 'very-deep', 'very-deep', 'professional_chart'),

-- X Series (Very deep neutral tones)
('#938981', 'X463', 'neutral', 'deep', 'deep', 'professional_chart'),
('#8F8478', 'X464', 'neutral', 'deep', 'deep', 'professional_chart'),
('#8B7F6F', 'X465', 'neutral', 'deep', 'deep', 'professional_chart'),
('#877A66', 'X466', 'neutral', 'deep', 'deep', 'professional_chart'),
('#83755D', 'X467', 'neutral', 'deep', 'deep', 'professional_chart'),
('#7F7054', 'X468', 'neutral', 'deep', 'deep', 'professional_chart'),
('#7B6B4B', 'X469', 'neutral', 'deep', 'deep', 'professional_chart'),
('#776642', 'X470', 'neutral', 'very-deep', 'very-deep', 'professional_chart'),
('#736139', 'X471', 'neutral', 'very-deep', 'very-deep', 'professional_chart'),
('#6F5C30', 'X472', 'neutral', 'very-deep', 'very-deep', 'professional_chart'),
('#6B5727', 'X473', 'neutral', 'very-deep', 'very-deep', 'professional_chart'),
('#67521E', 'X474', 'neutral', 'very-deep', 'very-deep', 'professional_chart'),

-- Y Series (Very deep warm tones)
('#867C75', 'Y463', 'warm', 'deep', 'deep', 'professional_chart'),
('#82776C', 'Y464', 'warm', 'deep', 'deep', 'professional_chart'),
('#7E7263', 'Y465', 'warm', 'deep', 'deep', 'professional_chart'),
('#7A6D5A', 'Y466', 'warm', 'deep', 'deep', 'professional_chart'),
('#766851', 'Y467', 'warm', 'deep', 'deep', 'professional_chart'),
('#726348', 'Y468', 'warm', 'very-deep', 'very-deep', 'professional_chart'),
('#6E5E3F', 'Y469', 'warm', 'very-deep', 'very-deep', 'professional_chart'),
('#6A5936', 'Y470', 'warm', 'very-deep', 'very-deep', 'professional_chart'),
('#66542D', 'Y471', 'warm', 'very-deep', 'very-deep', 'professional_chart'),
('#624F24', 'Y472', 'warm', 'very-deep', 'very-deep', 'professional_chart'),
('#5E4A1B', 'Y473', 'warm', 'very-deep', 'very-deep', 'professional_chart'),
('#5A4512', 'Y474', 'warm', 'very-deep', 'very-deep', 'professional_chart');