// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trbvlmzrnopvubizaacb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyYnZsbXpybm9wdnViaXphYWNiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODI0NTQsImV4cCI6MjA2NjQ1ODQ1NH0.rEBE5Zpom7zo38kyOLgKNv7TqR07-JGPA-1PwNmUY00";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);